### ISSUE TITLE
Fields in the form or [Aggregation]([Owner].[Table].[Column]) aren't being formatted properly

### ISSUE THREAD

**Issue by recipeshelf** [benlaan/sqlformat#12]
For example: "SELECT Count(HumanResources.Employee.EmployeeID) FROM HumanResources.Employee" doesn't work while "SELECT Count(Employee.EmployeeID) FROM Employee" works.

**Comment by benlaan** [comment]
@prasadtad If you mean that the output looks like this:

SELECT
    Count(
        HumanResources.Employee.EmployeeID
    )
FROM HumanResources.Employee


Then I agree with you! I'll fix this ASAP
