### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by prettydiff** [benlaan/sqlformat#27]
Are there plans to extend support for Unicode characters?  The Atom Beautify package is getting reports that sqlformat fails on some non-Latin characters:

https://github.com/Glavin001/atom-beautify/issues/1094

**Comment by benlaan** [comment]
Actually there is support for unicode in sqlformat! see https://github.com/benlaan/sqlformat/blob/master/Laan.SQL.Parser.Test/TestTokenizer.cs#L84

**Comment by vmuriart** [comment]
This can be closed. It should have been opened against [`sqlparse`](https://github.com/andialbrecht/sqlparse/issues/315). Sorry for the confusion
