### ISSUE TITLE
VS2017: Some of projects cannot be open

### ISSUE THREAD

**Issue by win32nipuh** [benlaan/sqlformat#33]
I tried to open and build the solution in VS2017 but received some errors and some of projects could not be open like these:

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.SQL.Formatter\Laan.Sql.Formatter.csproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\MSBuildTasks.1.5.0.235\tools\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Build\Common.targets

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.NHibernate.Appender\Laan.NHibernate.Appender.csproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\MSBuildTasks.1.5.0.235\tools\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Build\Common.targets

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.SQL.Parser\Laan.Sql.Parser.csproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\MSBuildTasks.1.5.0.235\tools\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Build\Common.targets

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.AddIns.Ssms\Laan.AddIns.Ssms.csproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\MSBuildTasks.1.5.0.235\tools\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Build\Common.targets

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.Sql.Tools.Installer\Laan.Sql.Tools.Installer.wixproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\WiX.Toolset.3.9.1208.0\tools\wix\wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.Sql.Tools.Installer\Laan.Sql.Tools.Installer.wixproj

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.SQL.Formatter\Laan.Sql.Formatter.csproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\MSBuildTasks.1.5.0.235\tools\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Build\Common.targets

E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Laan.SQL.Parser\Laan.Sql.Parser.csproj : error  : The imported project "E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\packages\MSBuildTasks.1.5.0.235\tools\MSBuild.Community.Tasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\MyProjects\SQLServer\SSMS_1\sqlformat-master\Build\Common.targets

**Comment by benlaan** [comment]
Looks like you need to restore your nuget packages.
